[colors.primary]
background = "#222222"
foreground = "#c2c2b0"

[colors.normal]
black = "#222222"
red = "#725F48"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"

[colors.bright]
black = "#666666"
red = "#725F48"
green = "#5f875f"
yellow = "#b36d43"
blue = "#78824b"
magenta = "#bb7744"
cyan = "#c9a554"
white = "#d7c483"
